# Syntax: https://www.redhat.com/en/topics/automation/what-is-yaml#:~:text=YAML%20is%20a%20human%2Dreadable,is%20for%20data%2C%20not%20documents.
# Services: https://docs.docker.com/reference/compose-file/services/

# ------------------------------------
# DEFINE SERVICES
# ------------------------------------

services:
  # 1. MARIADB SERVICE (database)
  mariadb:
    # Use 'inception' tag, as no tag defaults to 'latest' (forbidden)
    # Also avoids confusion with the official 'mariadb' image
    image: mariadb:inception

    build:
      context: ${MARIADB_CONTEXT}
      dockerfile: Dockerfile

    restart: always

    # Vars within the container, used when running it
    # Docker Compose automatically loads variables from a .env file in the same directory
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_ROOT_PASSWORD_FILE: /run/secrets/root_password
      DB_PASSWORD_FILE: /run/secrets/db_password

    secrets:
    # secrets are made available as files in container in /run/secrets/<secret_name>
      - root_password
      - db_password

    volumes:
      - db_data:/var/lib/mysql

    networks:
      - inception

# ------------------------------------
# DEFINE VOLUMES AND SECRETS
# ------------------------------------

volumes:
  db_data:
  wp_files:

networks:
  inception:

secrets:
  root_password:
    file: ${SECRET_DB_ROOT_PASS_FILE}

  db_password:
    file: ${SECRET_DB_PASS_FILE}
