# Base image for the container.
# Debian 12 ("Bookworm") is the latest stable version currently, but
# Debian 11 ("Bullseye") is the current penultimate stable version.
FROM		debian:bullseye

# Author
LABEL		author="aschenk"
